### ISSUE TITLE
Including `specklepy.api.operations` breaks AWS Lambda

### ISSUE THREAD

**Issue by hawkaa** [specklesystems/speckle-py#107]
Hi guys,

We come across a really quirky issue with this library and how it is deployed. On a scale from 1-10 I would rate it as 2 when it comes to how important it is, but I thought I would let you guys know.

### Expected vs. Actual Behavior

When including `specklepy.api.operations` the following stack trace is thrown:

```txt
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/datadog_lambda/handler.py", line 30, in <module>
    handler_module = import_module(modified_mod_name)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/import_lambdas/exchange2gltf.py", line 6, in <module>
    from .transform.speckle import get_base_from_raw_transport, get_trimesh_scene_from_base
  File "/var/task/import_lambdas/transform/speckle.py", line 3, in <module>
    from specklepy.api import operations
  File "/var/task/specklepy/api/operations.py", line 4, in <module>
    from specklepy.transports.sqlite import SQLiteTransport
  File "/var/task/specklepy/transports/sqlite.py", line 14, in <module>
    class SQLiteTransport(AbstractTransport):
  File "/var/task/specklepy/transports/sqlite.py", line 22, in SQLiteTransport
    __queue: Queue = Queue()
  File "/var/lang/lib/python3.8/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/var/lang/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
 ```

This only happens within an AWS lambda. Further information [here](https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda).

Expected behaviour is that this should not crash unless using SQLite transport explicitly.

### Reproduction Steps & System Config (win, osx, web, etc.)

Deploy and run the following file in an AWS lambda:

```python
from specklepy.api.operations import receive
```

### Proposed Solution (if any)

There are several ways to solve this. One way could be to try to not initialize the SQLIte libraries before the transport is created. Another way could be to do a best effort to load SQLIte, but if it crashes the error is ignored.

Dream solution I think is to add `sqlite` as an [pypi extra](https://stackoverflow.com/questions/52474931/what-is-extra-in-pypi-dependency).

Let me know what you think! :D

**Comment by izzylys** [comment]
Hey @hawkaa, thanks a lot for bringing this to my attention!

I haven't had a proper look at this yet, but here are some prelim thoughts.

The specklepy `SQLiteTransport` is by default used in both `operations.send` and `operations.receive` even if you are only providing a `ServerTransport`. This is because: (1) on send it is used as a local cache and (2) on receive it is used to check if you have received any of the incoming objects previously. You can however bypass this off by (1) setting `use_default_cache` to `False` on `send` and (2) by providing your server transport as both the `local` and `remote` transport on `receive`.

From the SO link you provided, it looks like the issue is actually with using the `multiprocessing.Queue`. We use `multiprocessing.Queue` in the `SQLiteTransport` and `queue.Queue` in the `ServerTransport` in order to speed up sending and receiving by performing actions in parallel. However, I believe this is actually commented out in the `SQLiteTransport` as there were some issues with it. We can remove the reference and see if that solves the issue since we aren't utilising the queue at the moment. Hopefully, the queue in the `ServerTransport` isn't a problem though...tbd.

**Comment by hawkaa** [comment]
Thank you. You are right. It is the multiprocessing.Queue causing the problems for us. multiproccesing is not supported in AWS lambda. And our use case might be special, so no need to make something specific for us.

However, would be nice with some fallback mechanism to a normal queue if multiprocessing queues cannot be used?

**Comment by izzylys** [comment]
I've just made a new release without the multiprocessing queue as it isn't being used atm. We can totes look at using just `queue.Queue` when reimplementing this.

Let me know if this resolves the prob and we can close this issue!

**Comment by hawkaa** [comment]
Hi. New stack trace:

```txt
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/datadog_lambda/handler.py", line 30, in <module>
    handler_module = import_module(modified_mod_name)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/import_lambdas/exchange2gltf.py", line 6, in <module>
    from .transform.speckle import get_base_from_raw_transport, get_trimesh_scene_from_base
  File "/var/task/import_lambdas/transform/speckle.py", line 3, in <module>
    from specklepy.api.operations import receive
  File "/var/task/specklepy/api/operations.py", line 101, in <module>
    obj_string: str, read_transport: AbstractTransport = SQLiteTransport()
  File "/var/task/specklepy/transports/sqlite.py", line 37, in __init__
    os.makedirs(self._base_path, exist_ok=True)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
 ```
 
 Seems like `SQLiteTransport()` is initialized on import. I didnt know python worked that way.
 
 I am out of steam for today but can investigate further tomorrow. Until now we just assemble the correct parts of `receive` ourselves which works really nicely.
 
 Sorry for using your time on this!

**Comment by izzylys** [comment]
Ah so it's a default arg for the `deserialize` function. I can take that out and do a check within the function instead so it is triggered later.

The issues from your stack trace is that the `SQLiteTransport` looks for your local speckle db and creates the path / db if it doesn't find it. However, your environment is read only so this fails. I can add a check in there for this case as well.

Note that you'll need to either make sure you're always filling in your own transports when available and don't let the operations use defaults as this will always create an `SQLiteTransport` causing you to run into these errors. If you are able to create a db somewhere else though so you can benefit from the local cache, you can provide the path on init of the `SQLiteTransport` using the `base_path` argument. This will create a `Speckle` dir at your target `base_path` containing the db `Objects` (though you can change the db name with the `scope` argument.

**Comment by hawkaa** [comment]
Hi,

I am sorry to spend so much of your time on this. I could obviously have tried to come up with a fix myself. I also didn't know that python initializes the default arguments on load. I should have spent more time researching the issue before opening up a ticket here.

Either way, the fix in #110 should be fixing our problems and overall improves the code usability. I am very grateful you took your time to have a look at this. I'll take the new version for a spin and let you know.

**Comment by hawkaa** [comment]
It works! Thank you!

**Comment by izzylys** [comment]
Woohoo, so glad it works for you now 🥳

And no probs at all dude; thanks for bringing it up in an issue. It's always helpful to get feedback and bug reports!
