### ISSUE TITLE
 http://speckle.xyz is not a compatible Speckle Server

### ISSUE THREAD

**Issue by MaximilianFranz** [specklesystems/speckle-py#92]
### Expected vs. Actual Behavior

I am trying to simply login to the demo speckle server to try some object serializations, but get this error:

```python
Traceback (most recent call last):
  File "/Users/max/Documents/modugen/speckle-py/example/using_speckle.py", line 7, in <module>
    client = SpeckleClient(host=account.serverInfo.url, use_ssl=False)
  File "/Users/max/Documents/modugen/speckle-py/specklepy/api/client.py", line 56, in __init__
    raise SpeckleException(f"{self.url} is not a compatible Speckle Server", ex)
specklepy.logging.exceptions.SpeckleException: SpeckleException: http://speckle.xyz is not a compatible Speckle Server
```

I've tried manually providing the Token I've created in the web app and also tried the Speckle Manager for Mac. 
With the Manager approach, I can retrieve the `Account` from the `SQLTransport` but using this code still get the error: 

```python 

from specklepy.api.client import SpeckleClient
from specklepy.api.credentials import get_default_account

account = get_default_account()
print(account)
client = SpeckleClient(host=account.serverInfo.url, use_ssl=False)
client.authenticate(account.token)

print(stream_list = client.stream.list())
```

Does the python client work with the beta server or do I have to run the server locally? 
#### Optional: Affected Projects

Does this issue propagate to other dependencies or dependents? If so, list them here!

**Comment by MaximilianFranz** [comment]
I actually just solved this issue myself but still posting it for reference. 

When using the speckle.xyz server for testing `use_ssl` has to be `True`. Make total sense, but I got a bind blind on the issue..
