### ISSUE TITLE
Fail to active SpeckleBlender 2.0 - path process error

### ISSUE THREAD

**Issue by CyrilWaechter** [specklesystems/speckle-py#96]
### Expected vs. Actual Behavior

Expected to be able to successfully activate SpeckleBlender 2.0 in Blender Add-ons UI but I get an error.

### Reproduction Steps & System Config (win, osx, web, etc.)
OS: Manjaro Linux
python: 3.9.5

1. Install `specklepy` from this repo in python site-packages
2. symlink `bpy_speckle` from [speckle-blender repo](https://github.com/specklesystems/speckle-blender) in `~/.config/blender/2.92/scripts/addons/bpy_speckle/`
3. Activate `SpeckleBlender 2.0` in Blender Add-ons

Error message:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/pkgutil.py", line 416, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/usr/lib/python3.9/site-packages/specklepy/api/resources')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/cyril/.config/blender/2.92/scripts/addons/bpy_speckle/__init__.py", line 56, in <module>
    from specklepy.api.client import SpeckleClient  # , SpeckleCache
  File "/usr/lib/python3.9/site-packages/specklepy/api/client.py", line 6, in <module>
    from specklepy.api import resources
  File "/usr/lib/python3.9/site-packages/specklepy/api/resources/__init__.py", line 8, in <module>
    for (_, name, _) in pkgutil.iter_modules([Path(__file__).parent]):
  File "/usr/lib/python3.9/pkgutil.py", line 130, in iter_modules
    for i in importers:
  File "/usr/lib/python3.9/pkgutil.py", line 420, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1601, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1476, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

### Proposed Solution (if any)

Except there is a better way path apparently needs to be converted to a string.

#### Optional: Affected Projects

* speckle-py
* speckle-blender

**Comment by izzylys** [comment]
Hello again 😅

Sorry, I misunderstood where the error was coming from and have transferred the issue back here. I've tested your fix locally and it all seems to still work fine on windows. I'd be very happy to merge in a pr for this fix! Thanks for catching this - I hadn't seen this error before as I only really work in windows.
